-- users 테이블에 CSV 컬럼 추가
USE auth_db;

-- 누락된 컬럼 추가
ALTER TABLE users 
ADD COLUMN company VARCHAR(100) DEFAULT NULL COMMENT '회사',
ADD COLUMN team VARCHAR(100) DEFAULT NULL COMMENT '팀',
ADD COLUMN distribution VARCHAR(100) DEFAULT NULL COMMENT '유통',
ADD COLUMN channel VARCHAR(100) DEFAULT NULL COMMENT '채널',
ADD COLUMN position VARCHAR(100) DEFAULT NULL COMMENT '직책';

-- 확인
DESCRIBE users;